### ISSUE TITLE
Issue with test_countries_with_team_size 

### ISSUE THREAD

**Issue by purplman** [LaravelDaily/Test-Eloquent-Relationships#28] opened 2021-11-25 17:39 UTC
I don't know how but some random query passes the test. 
This is what I commited :D 

`$countries = Country::whereHas('teams', function($q) {
    $q->av('size', 4);
})->get();`

**Comment by LoaiDev** [comment] 2021-11-25 18:21
I just cloned your repo. It seems that the problem is the response print outs the error page including the stack trace that contains that text therefore that's what is causing it.

**Comment by thinkverse** [comment] 2021-11-26 19:47
It might be too little too late submitting a fix for this now. Wish I caught this before when testing but it never caught my eye until I saw this issue. Anyways it will be up to @PovilasKorop if the fix I submitted will be merged or not so. For now, I'd suggest just writing the correct query and submitting your solutions anyway. 🤷‍♂️

**Comment by thinkverse** [comment] 2021-11-27 07:33
Fix was merged for future test takers. @purplman can close this issue now. 🙂

**Closed** 2021-11-27 12:55 UTC
